linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errname
    - gocheckcompilerdirectives
    - gosec
    - maintidx
    - misspell
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - sloglint
    - spancheck
    - unconvert
    - unparam
    - usestdlibvars
